<!DOCTYPE html>
<html>
<head>
<meta name="viewport" content="width=device-width, initial-scale=1.0"/>

<style>

</style>
</head>
<body onload="startGame()">
<div id="game-area">
    
    <div class="page-header">
      <h1>Welcome to Irregular Game</h1>
    </div>
    <div>Chose a correct answer</div>
    <div id="console"></div>
    
    <canvas id="wheel"></canvas>
    <div>
        <button onclick="pause()">Stop</button>
        <button onclick="play()">RUN</button>
    </div>
</div>


<p>Note: The angle property must be a radian. You can convert degrees into radians by using the formula x * Math.PI / 180</p>
</body>
</html>
